### ISSUE TITLE
Countries picker modal is not dismissible on web

### ISSUE THREAD

**Issue by OmarThinks** [kuasha420/react-native-paper-phone-number-input#3]
Thanks a lot for creating this awesome package.

But the countriues picker modal is not dismissable.

I mean, when we press on the countries picker on web, there is no way can close that modal (unless if we select a country).
On android, we can press the back button to close the modal.

I suggest adding a close button to the picker modal, when we press on this button it closes the modal.

**Comment by OmarThinks** [comment]
@kuasha420 
You are really making the package📦 really cross platform.
Actually, this is only really cross platform phone input package I found on NPM.
Thanks!
💪💯✅👍😁

**Comment by kuasha420** [comment]
Thanks for raising this @OmarThinks ! This is now available in the latest version. :tada:
