### ISSUE TITLE
Add the ability to specify countries that the user can select

### ISSUE THREAD

**Issue by AndreyButyrchik** [kuasha420/react-native-paper-phone-number-input#6]

**Comment by ahmed-gelemli** [comment]
Hi, I'm currently working on adding functionality to allow users to specify and select countries.

**Comment by ahmed-gelemli** [comment]
Sent PR, waiting for feedback. @kuasha420 @AndreyButyrchik

**Comment by AndreyButyrchik** [comment]
@ahmed-gelemli , PR looks good, exactly what I need

**Comment by kuasha420** [comment]
Thank you @AndreyButyrchik for raising this issue for this valuable feature and @ahmed-gelemli for the PR. This is now released in [v1.3.1](https://github.com/kuasha420/react-native-paper-phone-number-input/releases/tag/v1.3.1). 

There is a slight change in prop name from `onlyCountries` to `includeCountries` and a corresponding `excludeCountries` prop. See the details in the [readme](https://github.com/kuasha420/react-native-paper-phone-number-input?tab=readme-ov-file#props) for how to best use them. 

Thank you <3
